spring:
  datasource:
     # h2 database
#    driver-class-name: org.h2.Driver # h2 database 連接位址
#    url: jdbc:h2:mem:test;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE # 配置driver
#    initialize: true
#    sql-script-ecoding: UTF-8
    
    # oracle database
    url: jdbc:oracle:thin:@localhost:1521/ORCL # 配置driver
#    url: jdbc:oracle:thin:@61.216.84.220:1533:XE # 配置driver 連不上了
    username: system
    password: 123456
    initialize: true
    sql-script-ecoding: UTF-8

  jpa:
    show-sql: true
    # oracle database setting
    database: oracle 
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: update
    properties:
      # h2       
#      dialect: org.hibernate.dialect.H2Dialect
      # oracle 
      hibernate.format_sql: true

  h2:
    console:
      enabled: true
      settings:
        web-admin-password: sa

  thymeleaf:
    cache: false
    prefix: "classpath:/templates/app/"
    suffix: .html

  web:
    resources:
      static-locations:
        - classpath:/static/
  
#  security:
#    user:
#      name: admin
#      password: 123456

  jackson:
    serialization:
      fail-on-empty-beans: false

# @Slf4j      
#logging:
#  level:
#    ROOT: DEBUG
    
# server
server:
  port: 8080

